Nuke Developer Kit (NDK) 13.2.4: DD::Image::Plane Class Reference
DD::Image::Plane Class Reference
Public Member Functions
Plane ()
Plane (const Plane &plane)
Plane (const Vector3 &n, const Vector3 &p)
Plane (const Vector3 &p0, const Vector3 &p1, const Vector3 &p2)
float distance (const Vector3 &p) const
Public Attributes
Vector3 normal
float d
Detailed Description
A plane in 3D space (nx*x + ny*y + nz*z + d = 0)
Constructor & Destructor Documentation
DD::Image::Plane::Plane () inline
default constructor
DD::Image::Plane::Plane (const Plane & plane) inline
copy constructor
DD::Image::Plane::Plane (const Vector3 & n, const Vector3 & p) inline
define a plane from a normal and a point on the plane
References DD::Image::Vector3::dot().
DD::Image::Plane::Plane (const Vector3 & p0, const Vector3 & p1, const Vector3 & p2) inline
define a plane by three points
References DD::Image::Vector3::cross(), DD::Image::Vector3::dot(), and DD::Image::Vector3::normalize().
Member Function Documentation
float DD::Image::Plane::distance (const Vector3 & p) const inline
distance between point and a plane
References DD::Image::Vector3::dot().
Referenced by DD::Image::ViewFrustum::getVisibility().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk