Nuke Developer Kit (NDK) 13.2.4: DD::Image::CameraOp Class Reference
DD::Image::CameraOp Class Reference
Inherits DD::Image::AxisOp.
Inherited by DD::Image::DefaultCamera, and DD::Image::LightOp.
Public Types
enum {
LENS_PERSPECTIVE, LENS_ORTHOGRAPHIC, LENS_UV, LENS_SPHERICAL,
LENS_RENDER_CAMERA, LENS_USER_CAMERA
}
typedef void(LensFunc) (Scene *, CameraOp *, MatrixArray *transforms, const VArray &v, Vector4 &out, void *data)
typedef void(LensNFunc) (Scene *, CameraOp *, MatrixArray *transforms, VArray *vert_array, int n, void *data)
Public Types inherited from DD::Image::Op
enum HandlesMode { eNoHandles, eHandlesUncooked, eHandlesCooked, eHandlesMax }
enum PrevalidateResult { eFinished, eCancelled, eAbandoned }
This is a tribool return value. Do not extend.
enum HandleType {
eNone, eMouseLeftClick, eMouseRightClick, eMouseMove,
eMouseDrag, eMouseRelease, eSelectionChanged, eSelectionChangeFinished,
eHandleDragTranslate, eHandleDragRotate, eHandleDragScale, eHandleDragPivot,
eAllHandles
}
enum ViewableModes { eViewableMode2D, eViewableMode3D, eViewableMode3D_2DReference }
enum GenerateType {
OUTPUT_OP, ANY_CONTEXT, INPUT_OP, INPUT_OP_PEEK,
EXECUTABLE, EXECUTABLE_SKIP, EXECUTABLE_INPUT, UICONTEXT_ONLY
}
enum NodeContext { eNodeGraph, eTimeline, eOpGraph }
enum StatusFlags { StatusNone, StatusModal, StatusUseCallback }
enum PopUpScheme {
ePU_Never, ePU_Done, ePU_Once, ePU_Default,
ePU_Always
}
Pop-up schemes determine when pop-up messages are displayed for op errors.
enum VersionComponents { eMajor, eMinor, ePoint, eRevision }
Enum to help get the desired version component from the VersionInfo tuple.
typedef std::pair< int, DD::Image::Op * > Output
Combination of input number and pointer to Op.
typedef std::set< Output > OutputSet
Set of all outputs from this Op.
typedef std::map< Hash, std::vector< unsigned int > > ItemSelectionList
typedef bool(EventCallback) (Op *op, EventContext eventCtx)
using VersionInfo = std::tuple< int, int, int, int >
Contains version components with each index defined by the VersionComponents enum.
Public Member Functions
CameraOp (Node *node)
void _validate (bool for_real) override
void knobs (Knob_Callback) override
virtual void projection_knobs (Knob_Callback)
virtual void lens_knobs (Knob_Callback)
unsigned node_color () const override
void draw_handle (ViewerContext *) override
void hfov (double v)
double film_width () const
void film_width (double v)
double film_height () const
void film_height (double v)
double focal_length () const
void focal_length (double v)
double Near () const
void Near (double v)
double Far () const
void Far (double v)
double focal_point () const
void focal_point (double v)
double fstop () const
void fstop (double v)
int projection_mode () const
void projection_mode (int i)
virtual bool projection_is_linear (int mode) const
virtual LensFunc * lens_function (int mode) const
virtual LensNFunc * lensNfunction (int mode) const
double lens_distort_a () const
double lens_distort_b () const
double lens_distort_c () const
double lens_distort_D () const
double lens_distortion () const
double lens_power () const
bool lens_distort_enabled () const
const Vector2 & win_translate () const
const Vector2 & win_scale () const
double win_roll () const
const Matrix4 & projection () const
virtual Matrix4 projection (int mode) const
virtual Matrix4 projectionAt (const DD::Image::OutputContext &)
const char * Class () const override
const char * node_help () const override
HandlesMode doAnyHandles (ViewerContext *ctx) override
void build_handles (ViewerContext *) override
OpHints opHints () const override
Public Member Functions inherited from DD::Image::AxisOp
AxisOp (Node *, int defaultLookAtAxis=kAxisZPlus)
int minimum_inputs () const
int maximum_inputs () const
virtual const char * input_label (int input, char *) const
virtual Op * lookat_input () const
override from LookAt to add the look at pipe to input 1
virtual bool lookAtEnabled () const
by default all the axis look at pipe is disabled
void enableAxisKnobs (bool on)
void enableKnobs (const std::vector< std::string > &knobNames, bool on)
bool test_input (int, Op *) const
AxisOp * input0 () const
int display3d () const
bool selectable () const
void display3d (int v)
void selectable (bool v)
virtual bool isGuiInteractive (Axis_KnobI::Transformation knob) const
return true if a particular knob transformation is modifiable by user interaction in gui
Axis_KnobI * getAxis ()
const char * node_shape () const
int display3d ()
const Matrix4 & local () const
void matrix (const Matrix4 &m)
const Matrix4 & matrix () const
const Matrix4 & imatrix ()
virtual void matrixAt (const DD::Image::OutputContext &context, DD::Image::Matrix4 &matrix) const
virtual void print_info (std::ostream &o) const
Public Member Functions inherited from DD::Image::Op
PrevalidateResult preValidate (ViewerContext *ctx=nullptr, PreValidateContext *=nullptr)
Op * rootOp () const
bool preValidateAborted (int treeStartingVersion, PrevalidateResult &result) const
const OutputSet & getOutputs () const
return all the outputs of this node
virtual void setInputsValid (bool nowValid)
set whether the input ops are valid (are for the right context)
bool inputsValid () const
return whether the input ops are valid (are for the right context)
virtual bool can_clone () const
returns whether or not an op can be cloned in the dag
bool haveHash () const
return true if the hash() value is meaningful and globally unique
virtual std::vector< DD::Image::OutputContext > getPrevVersionsWanted () const
virtual const MetaData::Bundle & _fetchMetaData (const char *keyname)
const MetaData::Bundle & fetchMetaData (const char *keyname)
Node * node () const
DD::Image::NodeI * getNode () const
void node (Node *v)
Op * firstOp () const
void firstOp (Op *v)
Op * parent () const
void parent (Op *lpOp)
virtual void detach ()
node has been deleted in DAG
virtual void attach ()
node has been created in DAG
virtual void pre_write_knobs ()
int replace_knobs (Knob *afterthis, int n, void(*f)(void *, Knob_Callback), void *, const char *fileExt=nullptr)
int add_knobs (void(*f)(void *, Knob_Callback), void *, Knob_Callback)
void set_unlicensed ()
Knob * knob (const char *name) const
Knob * knob (int) const
bool pushed () const
bool panel_visible () const
bool node_disabled () const
bool node_selected () const
unsigned node_gl_color () const
void * field (const char *name)
void * field (const char *name, int &type)
void * set_field (const char *name, const void *source, int size)
void * get_field (const char *name, void *dest, int size)
void beginHandle (HandleType command, ViewerContext *ctx, EventCallback *cb, int index, float x=0, float y=0, float z=0, ViewerContext::Cursor cursor=ViewerContext::kNoCursor)
void endHandle (ViewerContext *ctx)
virtual int knob_changed (Knob *)
virtual int knob_change_finished (Knob *knob, bool changedByUser=true)
void addTime (OpTimer::Category category, long long microsecondsCPU, long long microsecondsWall, bool isTopLevel=true)
void getPerformanceInfo (OpTimer::Category category, OpTimer::PerformanceInfo &info) const
return the amount of CPU time taken by this op
virtual bool inputs_clockwise () const
whether unconnected inputs on the DAG should be arranged clockwise or anticlockwise (default)
virtual std::vector< int > input_order () const
virtual int inputArrows (int nodeInputs) const
bool script_command (const char *command, bool py=true, bool eval=true) const
bool script_expand (const char *str) const
HandlesMode anyHandles (ViewerContext *ctx)
void add_draw_handle (ViewerContext *)
virtual void add_input_handle (int input, ViewerContext *)
void add_op_handle (ViewerContext *ctx)
void add_knob_handle (Knob *, ViewerContext *)
virtual int getViewableModes () const
virtual int optional_input () const
int inputs () const
int node_inputs () const
Op * node_input (int, GenerateType=OUTPUT_OP) const
Op * node_input (int, GenerateType, const DD::Image::OutputContext *outputContext) const
Op * input_op (int n=0) const
virtual void inputs (int n)
Op * input (int) const
int inputNumber (int input, int offset) const
Op * input (int input, int offset) const
Op * input0 () const
return the primary input
Op * input1 () const
return the second input, if it exists
const std::vector< Op * > & getInputs () const
const std::vector< Op * > & getChildren () const
virtual void set_input (int i, Op *op, int input, int offset)
void set_input0 (Op *op)
void set_input (int i, Op *op)
void set_input (int i, Op &op)
void set_input (int input, int offset, Op *op)
const OutputContext & outputContext () const
virtual void setOutputContext (const OutputContext &c)
virtual void append (Hash &)
virtual float uses_input (int) const
virtual void build_splits ()
virtual int split_input (int) const
virtual const OutputContext & inputContext (int n, int offset, OutputContext &) const
virtual const OutputContext * inputUIContext (int n, OutputContext &) const
virtual Op * default_input (int) const
const Hash & hash () const
virtual bool frameTransformImplemented () const
virtual bool frameTransformDownstream (const OutputContext &context, unsigned int input, float inFrame, float &outFrame) const
virtual bool frameTransformUpstream (const OutputContext &context, unsigned int input, float outFrame, float &inFrame) const
virtual DopeItemFlags::Mask getDopeItemFlags () const
virtual bool shouldHideInDopeSheet (Knob *knob) const
virtual DD::Image::Knob * getDopeItemKnob () const
virtual ViewSet viewsProduced () const
virtual ViewSet viewsWantOn (int i) const
virtual ViewSet splitForViews () const
bool requested () const
void setRequested ()
void forgetRequestShallow ()
void forget_request ()
void forget_request (std::set< Op * > &forgotten)
DD::Image::Hash curveHash () const
bool opCurrent () const
virtual std::string input_longlabel (int) const
void node_redraw ()
void print_name (std::ostream &o) const
NodeContext nodeContext () const
std::string node_name () const
void invalidateSameHash ()
bool invalidate ()
bool invalidate (const Hash &hash)
bool update (const Box *=nullptr)
void asapUpdate ()
void asapUpdate (const Box &box, int direction=0)
void validate (bool for_real=true)
virtual void force_validate (bool for_real=true)
void update_handles () const
bool valid () const
Returns true if it has been validated - including if there was an error.
bool real_valid () const
Returns true if it has been real-validated - including if there was an error.
bool inErrorState () const
bool inInvalidState () const
bool opened () const
void open ()
void unopen ()
bool running () const
void running (bool v)
bool not_closed () const
void close ()
void callCloseAfter (double seconds)
void copyState (Op *input)
bool cached () const
void cached (bool b)
virtual bool inUse () const
virtual Executable * executable ()
void setKnobsToContext (const OutputContext &)
void gotoContext (const OutputContext &, bool update)
void progressFraction (double fraction, StatusFlags flags=StatusNone)
void progressFraction (int a, int b, StatusFlags flags=StatusNone)
void progressMessage (const char *fmt,...)
void progressModalMessage (const char *fmt,...)
void progressDismiss ()
int slowness () const
void slowness (int newval)
virtual bool firstEngineRendersWholeRequest () const
virtual bool updateUI (const OutputContext &context)
const Format & input_format () const
const OutputContext & uiContext () const
void error (const char *fmt,...)
void warning (const char *fmt,...)
void critical (const char *fmt,...)
void debug (const char *fmt,...)
void abort () const
Abort all trees the op is in.
bool aborted () const
True if one of the trees the op is in was aborted; ops should check this while processing and return quickly when true.
void cancel () const
Cancel all trees the op is in. Make sure you also call abort() to stop processing.
bool cancelled () const
True if one of the trees the op is in was cancelled (by user interaction)
bool addToTree (OpTree *lpTree)
Returns true if the op was added to the tree, or false if its reference count increased.
bool removeFromTree (OpTree *lpTree)
Returns false if the op was removed from the tree, or true if its reference count decreased.
bool isInTree (OpTree *lpTree) const
Checks if an op is in a particular tree, for debugging purposes.
bool isInAnyTree () const
Checks if an op is in any tree at all.
OpTreeHandler * getTreeHandler () const
Returns the treeHandler for a given Op.
bool hasError () const
bool opOrChildHasError () const
const Op * getErroredOp () const
void setPopUpScheme (PopUpScheme lScheme)
PopUpScheme getPopUpScheme () const
bool arePopUpsEnabled ()
Returns whether a pop-up should be enabled for the next message, modifying internal data when necessary.
OpMessageHandler & getMsgHandler ()
const OpMessageHandler & getMsgHandler () const
std::string getDebugInfo () const
Returns a string of debug information about the op. For internal use.
std::string getDetailedDebugInfo () const
bool tryValidate (bool for_real=true)
virtual Iop * iop ()
Cast to an Iop. This is much cheaper and safer than using dynamic_cast.
virtual const Iop * iop () const
virtual GeoOp * geoOp ()
Cast to a GeoOp. This is much cheaper and safer than using dynamic_cast.
virtual const GeoOp * geoOp () const
virtual ParticleOp * particleOp ()
Cast to a ParticleOp. This is much cheaper and safer than using dynamic_cast.
virtual const ParticleOp * particleOp () const
virtual DeepOnlyOp * deepOnlyOp ()
Cast to a DeepOnlyOp. This is much cheaper and safer than using dynamic_cast.
virtual const DeepOnlyOp * deepOnlyOp () const
virtual std::string getLibraryName () const
Return a label and version string to display library version info for the Node.
virtual VersionInfo getLibraryVersion () const
const std::string libraryDisplayName () const
virtual const char * displayName () const
virtual std::string docsPath () const
virtual bool onAction (const ViewerContext *c, const DD::Image::Flags f, void *d)
Op * get (const Description *description)
Public Member Functions inherited from DD::Image::LookAt
LookAt (int defaultLookAxis=kAxisZPlus)
void knobs (Knob_Callback f)
Adds the 'Look' tab and knobs for all the look at options.
int knobChanged (Op *parent, Knob *k)
disables the look at input is not present
void lookAt (Matrix4 &matrix)
performs the look at on the incoming matrix
void lookMatrixAt (const OutputContext &oc, Matrix4 &concatMatrix)
performs the look at on the incoming matrix for a given context
Static Public Member Functions
static void to_format (Matrix4 &, const Format *)
static void from_format (Matrix4 &, const Format *)
static CameraOp * default_camera ()
Static Public Member Functions inherited from DD::Image::Op
static int treeVersion ()
get the current tree version
static bool nukeBusy ()
is nuke processing something on a parallel thread?
static Op * create (Node *node, const char *name, Op *p_op)
static Op * create (const char *name, Op *p_op)
static void resetTimers ()
reset all the performance timers
static void setTimingEnabled (bool enabled)
turn performance timing on or off
static bool isTimingEnabled ()
return whether performance timing is on or not
static const char * script_result (bool py=false)
static void script_unlock ()
static void all_forget_request ()
static void new_request_pass ()
static double callPendingClose (double seconds)
static void clearPendingClose ()
static Op * error_op ()
static const char * error_message ()
static void clearAbortAndError ()
To be removed.
static void SetDefaultPopUpEnable (bool lEnable)
This is used by Nuke to indicate when ops using the default pop-up scheme should show pop-ups. Not recommended for customisation.
static std::string getVersionInfoStr (const VersionInfo &versionInfo)
Helper function to convert a VersionInfo tuple into a string.
static const Description * find_description (const char *name, const Op *op_)
static int message_f (char t, const char *,...)
static int message_vf (char t, const char *, va_list)
static void add_timeout (float t, TimeoutHandler, void *v=nullptr)
static void repeat_timeout (float t, TimeoutHandler, void *=nullptr)
static bool has_timeout (TimeoutHandler, void *=nullptr)
static void remove_timeout (TimeoutHandler, void *=nullptr)
Static Public Attributes
static const char * projection_modes []
static const char * projection_modes_renderer []
static const Description description
Static Public Attributes inherited from DD::Image::AxisOp
static const Description description
Static Public Attributes inherited from DD::Image::Op
static unsigned current_request_pass
static void(* node_redraw_cb)(const Op *)
static void(* print_name_cb)(std::ostream &, const Op *)
static void(* status_callback)(const Op *, float, float, const char *, StatusFlags)
static constexpr int kInvalidVersion
static constexpr VersionInfo kUnsetVersion
Protected Attributes
double focal_length_
double haperture_
double vaperture_
double near_
double far_
Near and far Z clipping planes.
Vector2 win_translate_
Window coords translate XY.
Vector2 win_scale_
Window coords scale XY.
double win_roll_
Window coords rotate Z.
Matrix4 projection_
Camera's projection matrix.
int projection_mode_
Camera lens projection mode.
double focal_point_
Focal point of camera.
double fstop_
camera fstop
bool use_vertical_lock_
double lens_distort_a_
double lens_distort_b_
double lens_distort_c_
double lens_distort_D_
double lens_distortion_
double lens_power_
bool lens_distort_enabled_
Protected Attributes inherited from DD::Image::AxisOp
Matrix4 localtransform_
Local matrix that Axis_Knob fills in.
Matrix4 local_
Matrix4 matrix_
Local matrix after look at performed.
Matrix4 imatrix_
Inverse object matrix.
bool inversion_updated
Whether imatrix_ is valid.
Axis_KnobI * axis_knob
reference to the transformation knob
WorldMatrixProvider * _worldMatrixProvider
int display3d_
GUI display setting.
bool selectable_
GUI selectable checkmark.
Protected Attributes inherited from DD::Image::Op
bool _haveHash
whether the _hash actually has been set by a call to invalidate(Hash) ever.
Protected Attributes inherited from DD::Image::LookAt
Matrix4 lookat_matrix_
Matrix for rotating to look at the look input.
Matrix4 my_local
For the Axis_Knob to store into.
bool my_transform_normals
int my_lookat_axis
bool my_rotate_x
bool my_rotate_y
bool my_rotate_z
bool my_lookat_use_quat
double my_lookat_strength
Additional Inherited Members
Public Attributes inherited from DD::Image::Op
const MetaData::Bundle * metaCache
Hash metaCacheHash
Protected Types inherited from DD::Image::LookAt
enum {
kAxisZPlus, kAxisZMinus, kAxisYPlus, kAxisYMinus,
kAxisXPlus, kAxisXMinus
}
Protected Member Functions inherited from DD::Image::Op
Op (Node *node)
The constructor is protected so only subclasses can create the base class.
virtual void _invalidate ()
virtual void _open ()
virtual void _close ()
Op * create (Node *node, const char *name)
Op * create (const char *name)
HandlesMode anyInputHandles (ViewerContext *)
return if any of the inputs (recursively) wish to draw handles
HandlesMode anyKnobHandles (ViewerContext *)
return if any of the knobs on this node wish to draw handles
void build_input_handles (ViewerContext *)
void build_knob_handles (ViewerContext *)
void disallowNoTrees ()
Call this to tell the op that it should always have op trees for normal behaviour (for internal use)
virtual PrevalidateResult doPreValidate (ViewerContext *ctx=nullptr, PreValidateContext *=nullptr)
Protected Member Functions inherited from DD::Image::LookAt
void perform_lookat (Matrix4 &concatMatrix, const Matrix4 &axisMatrix)
Static Protected Attributes inherited from DD::Image::LookAt
static const char *const ms_lookat_axis_choices []
Detailed Description
Op that defines a 3D camera.
Member Typedef Documentation
typedef void(DD::Image::CameraOp::LensFunc) (Scene *, CameraOp *, MatrixArray *transforms, const VArray &v, Vector4 &out, void *data)
Lens Projection/Distortion Function Type
Member Enumeration Documentation
anonymous enum
Enumerator
LENS_PERSPECTIVE
Standard perspective projection.
LENS_ORTHOGRAPHIC
Standard orthographic projection.
LENS_UV
Replace screen XY with UV coordinate.
LENS_SPHERICAL
360x180 world spherically projected around camera
LENS_RENDER_CAMERA
Renderer uses this option.
LENS_USER_CAMERA
Camera user projection.
Member Function Documentation
void CameraOp::draw_handle (ViewerContext * ctx) override virtual
Draws a lovely camera, I think it is a Mitchell.
Reimplemented from DD::Image::AxisOp.
Reimplemented in DD::Image::LightOp, and DD::Image::ComplexLightOp.
References DD::Image::Matrix4::array(), DD::Image::ViewerContext::display3d(), DD::Image::AxisOp::display3d_, DD::Image::Vector4::divide_w(), DD::Image::ViewerContext::draw_hidden_lines(), DD::Image::ViewerContext::draw_lines(), DD::Image::ViewerContext::draw_solid(), DD::Image::ViewerContext::fg_color(), focal_point_, DD::Image::gl_boxf(), DD::Image::gl_cylinderf(), DD::Image::gl_text(), DD::Image::glColor(), DD::Image::ViewerContext::hit_detect(), DD::Image::ViewerContext::icon_size(), DD::Image::Matrix4::inverse(), LENS_PERSPECTIVE, LENS_UV, DD::Image::ViewerContext::modelmatrix, DD::Image::ViewerContext::node_color(), DD::Image::Op::node_selected(), DD::Image::Op::print_name(), projection(), projection_, projection_mode_, DD::Image::AxisOp::selectable_, DD::Image::style_needs_wireframe(), DD::Image::Matrix4::transform(), DD::Image::ViewerContext::viewer_mode(), and DD::Image::VIEWER_PERSP.
bool CameraOp::projection_is_linear (int mode) const virtual
Returns true if current projection mode can be described linearly. This only true for perspective and orthographic modes if no lens distortion in being done.
References LENS_ORTHOGRAPHIC, LENS_PERSPECTIVE, LENS_SPHERICAL, and LENS_UV.
Referenced by DD::Image::rTriangle::add_to_render().
CameraOp::LensFunc * CameraOp::lens_function (int mode) const virtual
Returns the current lens function used to distort vertices during software rendering. Single VArray version returns a Vector4.
References LENS_ORTHOGRAPHIC, LENS_PERSPECTIVE, LENS_SPHERICAL, and LENS_UV.
CameraOp::LensNFunc * CameraOp::lensNfunction (int mode) const virtual
Returns the current lens function used to distort vertices during software rendering. Array function version that accepts a pointer to an array of VArray structures and thier number.
References LENS_ORTHOGRAPHIC, LENS_PERSPECTIVE, LENS_SPHERICAL, and LENS_UV.
Referenced by DD::Image::Render::_validate().
void CameraOp::to_format (Matrix4 & matrix, const Format * format) static
Multiply the passed matrix by the necessary transformation to put x=-1 at the left edge of the format, +1 at the right, and to center it vertically, and compensate for any pixel aspect. The output z and w are left unchanged.
Most Iops will need to do this using their output format to get the actual transformation from input space to output space. You would do this first, then multiply by the projection*local*parent.
References DD::Image::Format::pixel_aspect(), DD::Image::Box::r(), DD::Image::Matrix4::scale(), DD::Image::Box::t(), DD::Image::Matrix4::translate(), DD::Image::Box::w(), DD::Image::Box::x(), and DD::Image::Box::y().
void CameraOp::from_format (Matrix4 & matrix, const Format * format) static
Opposite transformation of to_format(). Multiplies the passed matrix by a transformation that scales the input format to go from x = -1 to x = 1 and to center it vertically around y = 0, and to remove any pixel aspect ratio. You multiply by this matrix last.
The 3DCard iop scales further so the image covers a range so that if the camera lens and "taking lens" are equal the image fills the field of view.
References DD::Image::Format::pixel_aspect(), DD::Image::Box::r(), DD::Image::Matrix4::scale(), DD::Image::Box::t(), DD::Image::Matrix4::translate(), DD::Image::Box::w(), DD::Image::Box::x(), and DD::Image::Box::y().
Referenced by DD::Image::GeoOp::build_matrix_handles().
const Matrix4 & DD::Image::CameraOp::projection () const inline
Returns a transformation to an output image due to the camera lens. This will transform points at the left edge of the film to an x value of -1, and points at the right to an x value of +1. Vertically it will produce a square transform, ie for most film shapes the +/-1 value for y is outside the top or bottom of the rectangular frame.
The z output of this transformation is set to match the OpenGL near/far clipping planes at -1 and +1. These planes may be chosen by Nuke to make a nice display with OpenGL, and you should avoid having them have any effect on the output image. If you want the actual distance to an object from the camera, the w output of this transformation will give you that.
For most uses you want to multiply projection()*xform() and pass the result through to_format() to get the transformation from world space to output pixels.
Referenced by draw_handle(), and projection().
Matrix4 CameraOp::projection (int mode) const virtual
Return camera projection matrix for a particular projection mode. It needs to be overridden if subclasses implement a different logic to calculate the projection matrix.
References far_, LENS_PERSPECTIVE, projection(), DD::Image::Matrix4::projection(), radians(), DD::Image::Matrix4::rotateZ(), DD::Image::Matrix4::scale(), DD::Image::Matrix4::translate(), win_roll_, win_scale_, and win_translate_.
CameraOp * CameraOp::default_camera () static
Return a default camera that can be used when the there is no camera attached to your renderer. This camera is at the origin, looking along -z, and has a lens ratio focal_length/film_width of 1.
Referenced by DD::Image::Render::_validate(), DD::Image::RenderScene::build_handles(), and DD::Image::RenderScene::render_camera().
OpHints CameraOp::opHints () const override virtual
Return hints to control when and how this op will be evaluated by the top-down system.
Reimplemented from DD::Image::Op.
References DD::Image::eChainable.
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk