Nuke Developer Kit (NDK) 13.2.4: DD::Image::LUTInfo Class Reference
DD::Image::LUTInfo Class Reference abstract
Inherited by DD::Image::ReaderImpl, and DD::Image::WriterImpl.
Public Member Functions
LUTInfo (Op *pOp)
void registerForCallbacks ()
This must be called after the Reader/Writer is constructed.
void unregisterForCallbacks ()
void setLUTDataTypeHint (const LUT::DataType type) const
LUT::DataType lutDataTypeHint () const
std::string getBuiltinLUTName (std::string &mappedStringOut)
std::string updateColorspaceDefaultValue ()
util function for calling updateColorspaceDefaultValue()
std::string stripCascadingPrefix (const std::string &) const
strip off cascading menus prefix
virtual LUT * defaultLut () const =0
must return the LUT pointer used by the LUTInfo derived class
Protected Attributes
std::string _overrideColorspaceName
Detailed Description
Private, hidden implementation for sharing information about LUTs with Read and Write Ops and Nuke
Member Function Documentation
void LUTInfo::unregisterForCallbacks ()
This must be called before the Reader/Writer is destructed and only if you want to unregister the callbacks earlier
std::string LUTInfo::getBuiltinLUTName (std::string & mappedStringOut)
Get the name of the given builtin LUT. Will also use the provided writer (if any) to find the equivalent OCIO mapped name
References DD::Image::LUT::builtin_names, defaultLut(), and DD::Image::LUT::GetBuiltinLUT().
Referenced by updateColorspaceDefaultValue().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk