Nuke Developer Kit (NDK) 13.2.4: DD::Image::ImagePlaneDescriptor Class Reference
DD::Image::ImagePlaneDescriptor Class Reference
Inherited by DD::Image::GenericImagePlaneDescriptor, and DD::Image::ImagePlane.
Public Member Functions
ImagePlaneDescriptor (const DD::Image::Box &bounds, bool packed, DD::Image::ChannelSet mask, int nComps)
DD::Image::Box bounds () const
ChannelSet channels () const
bool packed () const
int nComps () const
bool intersects (const ImagePlaneDescriptor &other) const
bool intersects (int y, int t) const
bool satisfiedBy (const ImagePlaneDescriptor &candidate)
Protected Attributes
DD::Image::Box _bounds
bool _packed
ChannelSet _mask
int _nComps
Detailed Description
Class to describe an image plane. Contains a bounding box, a set of channels, and whether or not the image plane is packed or not.
Member Function Documentation
bool DD::Image::ImagePlaneDescriptor::intersects (const ImagePlaneDescriptor & other) const inline
whether this image plane intersects in channels and in bounding box with the other.
References DD::Image::Box::r(), DD::Image::Box::t(), DD::Image::Box::x(), and DD::Image::Box::y().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk