Nuke Developer Kit (NDK) 13.2.4: DD::Image::DeepSample Class Reference
DD::Image::DeepSample Class Reference
helper class representing a small float vector, one for each channel in a set
Public Member Functions
DeepSample (const ChannelMap &map)
initialise based on a ChannelMap. Set all samples to zero.
DeepSample (const ChannelMap &map, const DeepPixel &pixel, int sample, bool fetchOrdered=false)
void operator= (const DeepSample &other)
void operator= (DeepSample &other)
bool operator== (DeepSample &other)
float & operator[] (Channel z)
access the float for a particular channel
const float & operator[] (Channel z) const
access the float for a particular channel
SampleContainer::iterator begin ()
SampleContainer::iterator end ()
size_t size ()
Detailed Description
helper class representing a small float vector, one for each channel in a set
Constructor & Destructor Documentation
DD::Image::DeepSample::DeepSample (const ChannelMap & map, const DeepPixel & pixel, int sample, bool fetchOrdered = false) inline
initialise based on a sample from a DeepPixel. if fetchOrdered is true it will use getOrderedSample, otherwise getUnorderedSample
References DD::Image::DeepPixel::channels(), DD::Image::ChannelMap::contains(), DD::Image::DeepPixel::getOrderedSample(), and DD::Image::DeepPixel::getUnorderedSample().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk