Nuke Developer Kit (NDK) 13.2.4: DD::Image::SourceGeo Class Reference
DD::Image::SourceGeo Class Reference abstract
Inherits DD::Image::NullGeo.
Inherited by DD::Image::ReadGeo.
Public Member Functions
SourceGeo (Node *)
Iop * input_iop () const
virtual Iop * default_material_iop () const
int minimum_inputs () const
int maximum_inputs () const
Op * default_input (int) const
bool test_input (int input, Op *op) const
const char * input_label (int input, char *buffer) const
void knobs (Knob_Callback)
void build_input_handles (ViewerContext *)
const char * Class () const
const char * node_help () const
virtual void init_geoinfo_parms (Scene &, GeometryList &)
bool render_checkmark () const
Public Member Functions inherited from DD::Image::NullGeo
NullGeo (Node *node)
Public Member Functions inherited from DD::Image::GeoOp
virtual ~GeoOp ()
Scene * scene () const
void build_scene (Scene &scene)
void get_geometry (Scene &, GeometryList &out)
void setupScene ()
bool evaluate_transform (int obj, GeometryList &out, bool transform_normals=true)
GeoOp * input (int n) const
GeoOp * input0 () const
GeoOp * input1 () const
const char * node_shape () const override
unsigned node_color () const override
void shadow_knobs (Knob_Callback f)
void knobs (Knob_Callback, bool sourcegeo, bool geoselectSaves=false)
int knob_changed (Knob *k) override
virtual void print_info (std::ostream &o)
unsigned objects () const
unsigned vertices (int obj) const
std::vector< GeoInfo::Cache > & getCacheList ()
HandlesMode doAnyHandles (ViewerContext *) override
void build_matrix_handles (ViewerContext *ctx, const Matrix4 *localMatrix=nullptr)
void build_handles (ViewerContext *ctx) override
virtual void select_geometry (ViewerContext *, GeometryList &scene_objects)
void assign_drawlists (int obj, GeoInfo &info)
Display3DMode display3d () const
RenderMode render_mode () const
bool selectable () const
virtual bool selection3DChanged (ViewerContext *ctx)
virtual bool selection3DCleared ()
virtual bool selection3DMouseDown (ViewerContext *ctx)
virtual bool selection3DMouseUp (ViewerContext *ctx)
virtual bool selection3DMouseDrag (ViewerContext *ctx)
const Hash & hash (int i) const
const GeometryMask & rebuild_mask () const
bool rebuild (const GeometryMask &m=GeometryMask(Mask_All_Geometry)) const
void set_rebuild (const GeometryMask &m)
void clear_rebuild (const GeometryMask &m)
const GeneralInfo & generalInfo () const override
GeoOp * geoOp () override
Cast to a GeoOp. This is much cheaper and safer than using dynamic_cast.
const GeoOp * geoOp () const override
OpHints opHints () const override
Return hints to control when and how this op will be evaluated by the top-down system.
Public Member Functions inherited from DD::Image::Op
PrevalidateResult preValidate (ViewerContext *ctx=nullptr, PreValidateContext *=nullptr)
Op * rootOp () const
bool preValidateAborted (int treeStartingVersion, PrevalidateResult &result) const
const OutputSet & getOutputs () const
return all the outputs of this node
virtual void setInputsValid (bool nowValid)
set whether the input ops are valid (are for the right context)
bool inputsValid () const
return whether the input ops are valid (are for the right context)
virtual bool can_clone () const
returns whether or not an op can be cloned in the dag
bool haveHash () const
return true if the hash() value is meaningful and globally unique
virtual std::vector< DD::Image::OutputContext > getPrevVersionsWanted () const
virtual const MetaData::Bundle & _fetchMetaData (const char *keyname)
const MetaData::Bundle & fetchMetaData (const char *keyname)
Node * node () const
DD::Image::NodeI * getNode () const
void node (Node *v)
Op * firstOp () const
void firstOp (Op *v)
Op * parent () const
void parent (Op *lpOp)
virtual void detach ()
node has been deleted in DAG
virtual void attach ()
node has been created in DAG
virtual void pre_write_knobs ()
int replace_knobs (Knob *afterthis, int n, void(*f)(void *, Knob_Callback), void *, const char *fileExt=nullptr)
int add_knobs (void(*f)(void *, Knob_Callback), void *, Knob_Callback)
void set_unlicensed ()
Knob * knob (const char *name) const
Knob * knob (int) const
bool pushed () const
bool panel_visible () const
bool node_disabled () const
bool node_selected () const
unsigned node_gl_color () const
void * field (const char *name)
void * field (const char *name, int &type)
void * set_field (const char *name, const void *source, int size)
void * get_field (const char *name, void *dest, int size)
void beginHandle (HandleType command, ViewerContext *ctx, EventCallback *cb, int index, float x=0, float y=0, float z=0, ViewerContext::Cursor cursor=ViewerContext::kNoCursor)
void endHandle (ViewerContext *ctx)
virtual int knob_change_finished (Knob *knob, bool changedByUser=true)
void addTime (OpTimer::Category category, long long microsecondsCPU, long long microsecondsWall, bool isTopLevel=true)
void getPerformanceInfo (OpTimer::Category category, OpTimer::PerformanceInfo &info) const
return the amount of CPU time taken by this op
virtual bool inputs_clockwise () const
whether unconnected inputs on the DAG should be arranged clockwise or anticlockwise (default)
virtual std::vector< int > input_order () const
virtual int inputArrows (int nodeInputs) const
bool script_command (const char *command, bool py=true, bool eval=true) const
bool script_expand (const char *str) const
HandlesMode anyHandles (ViewerContext *ctx)
void add_draw_handle (ViewerContext *)
virtual void draw_handle (ViewerContext *)
virtual void add_input_handle (int input, ViewerContext *)
void add_op_handle (ViewerContext *ctx)
void add_knob_handle (Knob *, ViewerContext *)
virtual int getViewableModes () const
virtual int optional_input () const
int inputs () const
int node_inputs () const
Op * node_input (int, GenerateType=OUTPUT_OP) const
Op * node_input (int, GenerateType, const DD::Image::OutputContext *outputContext) const
Op * input_op (int n=0) const
virtual void inputs (int n)
Op * input (int) const
int inputNumber (int input, int offset) const
Op * input (int input, int offset) const
Op * input0 () const
return the primary input
Op * input1 () const
return the second input, if it exists
const std::vector< Op * > & getInputs () const
const std::vector< Op * > & getChildren () const
virtual void set_input (int i, Op *op, int input, int offset)
void set_input0 (Op *op)
void set_input (int i, Op *op)
void set_input (int i, Op &op)
void set_input (int input, int offset, Op *op)
const OutputContext & outputContext () const
virtual void setOutputContext (const OutputContext &c)
virtual void append (Hash &)
virtual float uses_input (int) const
virtual void build_splits ()
virtual int split_input (int) const
virtual const OutputContext & inputContext (int n, int offset, OutputContext &) const
virtual const OutputContext * inputUIContext (int n, OutputContext &) const
const Hash & hash () const
virtual bool frameTransformImplemented () const
virtual bool frameTransformDownstream (const OutputContext &context, unsigned int input, float inFrame, float &outFrame) const
virtual bool frameTransformUpstream (const OutputContext &context, unsigned int input, float outFrame, float &inFrame) const
virtual DopeItemFlags::Mask getDopeItemFlags () const
virtual bool shouldHideInDopeSheet (Knob *knob) const
virtual DD::Image::Knob * getDopeItemKnob () const
virtual ViewSet viewsProduced () const
virtual ViewSet viewsWantOn (int i) const
virtual ViewSet splitForViews () const
bool requested () const
void setRequested ()
void forgetRequestShallow ()
void forget_request ()
void forget_request (std::set< Op * > &forgotten)
DD::Image::Hash curveHash () const
bool opCurrent () const
virtual std::string input_longlabel (int) const
void node_redraw ()
void print_name (std::ostream &o) const
NodeContext nodeContext () const
std::string node_name () const
void invalidateSameHash ()
bool invalidate ()
bool invalidate (const Hash &hash)
bool update (const Box *=nullptr)
void asapUpdate ()
void asapUpdate (const Box &box, int direction=0)
void validate (bool for_real=true)
virtual void force_validate (bool for_real=true)
void update_handles () const
bool valid () const
Returns true if it has been validated - including if there was an error.
bool real_valid () const
Returns true if it has been real-validated - including if there was an error.
bool inErrorState () const
bool inInvalidState () const
bool opened () const
void open ()
void unopen ()
bool running () const
void running (bool v)
bool not_closed () const
void close ()
void callCloseAfter (double seconds)
void copyState (Op *input)
bool cached () const
void cached (bool b)
virtual bool inUse () const
virtual Executable * executable ()
void setKnobsToContext (const OutputContext &)
void gotoContext (const OutputContext &, bool update)
void progressFraction (double fraction, StatusFlags flags=StatusNone)
void progressFraction (int a, int b, StatusFlags flags=StatusNone)
void progressMessage (const char *fmt,...)
void progressModalMessage (const char *fmt,...)
void progressDismiss ()
int slowness () const
void slowness (int newval)
virtual bool firstEngineRendersWholeRequest () const
virtual bool updateUI (const OutputContext &context)
const Format & input_format () const
const OutputContext & uiContext () const
void error (const char *fmt,...)
void warning (const char *fmt,...)
void critical (const char *fmt,...)
void debug (const char *fmt,...)
void abort () const
Abort all trees the op is in.
bool aborted () const
True if one of the trees the op is in was aborted; ops should check this while processing and return quickly when true.
void cancel () const
Cancel all trees the op is in. Make sure you also call abort() to stop processing.
bool cancelled () const
True if one of the trees the op is in was cancelled (by user interaction)
bool addToTree (OpTree *lpTree)
Returns true if the op was added to the tree, or false if its reference count increased.
bool removeFromTree (OpTree *lpTree)
Returns false if the op was removed from the tree, or true if its reference count decreased.
bool isInTree (OpTree *lpTree) const
Checks if an op is in a particular tree, for debugging purposes.
bool isInAnyTree () const
Checks if an op is in any tree at all.
OpTreeHandler * getTreeHandler () const
Returns the treeHandler for a given Op.
bool hasError () const
bool opOrChildHasError () const
const Op * getErroredOp () const
void setPopUpScheme (PopUpScheme lScheme)
PopUpScheme getPopUpScheme () const
bool arePopUpsEnabled ()
Returns whether a pop-up should be enabled for the next message, modifying internal data when necessary.
OpMessageHandler & getMsgHandler ()
const OpMessageHandler & getMsgHandler () const
std::string getDebugInfo () const
Returns a string of debug information about the op. For internal use.
std::string getDetailedDebugInfo () const
bool tryValidate (bool for_real=true)
virtual Iop * iop ()
Cast to an Iop. This is much cheaper and safer than using dynamic_cast.
virtual const Iop * iop () const
virtual ParticleOp * particleOp ()
Cast to a ParticleOp. This is much cheaper and safer than using dynamic_cast.
virtual const ParticleOp * particleOp () const
virtual DeepOnlyOp * deepOnlyOp ()
Cast to a DeepOnlyOp. This is much cheaper and safer than using dynamic_cast.
virtual const DeepOnlyOp * deepOnlyOp () const
virtual std::string getLibraryName () const
Return a label and version string to display library version info for the Node.
virtual VersionInfo getLibraryVersion () const
const std::string libraryDisplayName () const
virtual const char * displayName () const
virtual std::string docsPath () const
virtual bool onAction (const ViewerContext *c, const DD::Image::Flags f, void *d)
Op * get (const Description *description)
Protected Member Functions
void render_checkmark (bool v)
Only constructors should call this, unless knobs() is not called.
void build_matrix_handles (ViewerContext *ctx, Matrix4 localMatrix)
void get_geometry_hash ()
void geometry_engine (Scene &, GeometryList &out)
virtual void create_geometry (Scene &, GeometryList &out)=0
virtual void updateGeneralInfo ()
Protected Member Functions inherited from DD::Image::GeoOp
GeoOp (Node *)
Base class constructor.
void _validate (bool for_real) override
void display3d (Display3DMode v)
void selectable (bool v)
void render_mode (RenderMode v)
void backface_culling (int v)
void update_geometry_hashes ()
void delete_cache ()
void synchronize_cache (GeometryList &out)
void delete_allocations (GeoInfo::Cache &cache)
void add_draw_geometry (ViewerContext *)
Protected Member Functions inherited from DD::Image::Op
Op (Node *node)
The constructor is protected so only subclasses can create the base class.
virtual void _invalidate ()
virtual void _open ()
virtual void _close ()
Op * create (Node *node, const char *name)
Op * create (const char *name)
HandlesMode anyInputHandles (ViewerContext *)
return if any of the inputs (recursively) wish to draw handles
HandlesMode anyKnobHandles (ViewerContext *)
return if any of the knobs on this node wish to draw handles
void build_input_handles (ViewerContext *)
void build_knob_handles (ViewerContext *)
void disallowNoTrees ()
Call this to tell the op that it should always have op trees for normal behaviour (for internal use)
virtual PrevalidateResult doPreValidate (ViewerContext *ctx=nullptr, PreValidateContext *=nullptr)
Additional Inherited Members
Public Types inherited from DD::Image::Op
enum HandlesMode { eNoHandles, eHandlesUncooked, eHandlesCooked, eHandlesMax }
enum PrevalidateResult { eFinished, eCancelled, eAbandoned }
This is a tribool return value. Do not extend.
enum HandleType {
eNone, eMouseLeftClick, eMouseRightClick, eMouseMove,
eMouseDrag, eMouseRelease, eSelectionChanged, eSelectionChangeFinished,
eHandleDragTranslate, eHandleDragRotate, eHandleDragScale, eHandleDragPivot,
eAllHandles
}
enum ViewableModes { eViewableMode2D, eViewableMode3D, eViewableMode3D_2DReference }
enum GenerateType {
OUTPUT_OP, ANY_CONTEXT, INPUT_OP, INPUT_OP_PEEK,
EXECUTABLE, EXECUTABLE_SKIP, EXECUTABLE_INPUT, UICONTEXT_ONLY
}
enum NodeContext { eNodeGraph, eTimeline, eOpGraph }
enum StatusFlags { StatusNone, StatusModal, StatusUseCallback }
enum PopUpScheme {
ePU_Never, ePU_Done, ePU_Once, ePU_Default,
ePU_Always
}
Pop-up schemes determine when pop-up messages are displayed for op errors.
enum VersionComponents { eMajor, eMinor, ePoint, eRevision }
Enum to help get the desired version component from the VersionInfo tuple.
typedef std::pair< int, DD::Image::Op * > Output
Combination of input number and pointer to Op.
typedef std::set< Output > OutputSet
Set of all outputs from this Op.
typedef std::map< Hash, std::vector< unsigned int > > ItemSelectionList
typedef bool(EventCallback) (Op *op, EventContext eventCtx)
using VersionInfo = std::tuple< int, int, int, int >
Contains version components with each index defined by the VersionComponents enum.
Static Public Member Functions inherited from DD::Image::GeoOp
static void transform_points (PointList *out, const PointList *in, const Matrix4 &)
static void transform_points (PointList *out, const PointList *in, int start, int end, const Matrix4 &)
static void clear_drawlist_trashbin ()
Static Public Member Functions inherited from DD::Image::Op
static int treeVersion ()
get the current tree version
static bool nukeBusy ()
is nuke processing something on a parallel thread?
static Op * create (Node *node, const char *name, Op *p_op)
static Op * create (const char *name, Op *p_op)
static void resetTimers ()
reset all the performance timers
static void setTimingEnabled (bool enabled)
turn performance timing on or off
static bool isTimingEnabled ()
return whether performance timing is on or not
static const char * script_result (bool py=false)
static void script_unlock ()
static void all_forget_request ()
static void new_request_pass ()
static double callPendingClose (double seconds)
static void clearPendingClose ()
static Op * error_op ()
static const char * error_message ()
static void clearAbortAndError ()
To be removed.
static void SetDefaultPopUpEnable (bool lEnable)
This is used by Nuke to indicate when ops using the default pop-up scheme should show pop-ups. Not recommended for customisation.
static std::string getVersionInfoStr (const VersionInfo &versionInfo)
Helper function to convert a VersionInfo tuple into a string.
static const Description * find_description (const char *name, const Op *op_)
static int message_f (char t, const char *,...)
static int message_vf (char t, const char *, va_list)
static void add_timeout (float t, TimeoutHandler, void *v=nullptr)
static void repeat_timeout (float t, TimeoutHandler, void *=nullptr)
static bool has_timeout (TimeoutHandler, void *=nullptr)
static void remove_timeout (TimeoutHandler, void *=nullptr)
Public Attributes inherited from DD::Image::Op
const MetaData::Bundle * metaCache
Hash metaCacheHash
Static Public Attributes inherited from DD::Image::Op
static unsigned current_request_pass
static void(* node_redraw_cb)(const Op *)
static void(* print_name_cb)(std::ostream &, const Op *)
static void(* status_callback)(const Op *, float, float, const char *, StatusFlags)
static constexpr int kInvalidVersion
static constexpr VersionInfo kUnsetVersion
Protected Attributes inherited from DD::Image::GeoOp
Hash geo_hash [Group_Last]
Scene * scene_
Points to scene if it is turned on.
GeneralInfo info_
std::vector< GeoInfo::Cache > cache_list
Geometry cache structures.
Hash cache_hash [Group_Last]
Cache out-of-dateness hashes.
GeometryMask rebuild_mask_
What groups need updating.
bool cache_resursive
Hash cache_build_hash
int display3d_
GUI display setting.
bool selectable_
GUI selectable checkmark.
int render_mode_
Render setting.
int backface_culling_
Backface cull setting.
bool cast_shadow_
bool receive_shadow_
Protected Attributes inherited from DD::Image::Op
bool _haveHash
whether the _hash actually has been set by a call to invalidate(Hash) ever.
Static Protected Attributes inherited from DD::Image::GeoOp
static Hash sInitialGeoHash
static Hash sInitialCacheHash
Detailed Description
Subclass of GeoOp that does not take another GeoOp as input. This alters the control panel knobs and tooltips slightly to avoid references to the input geometry.
Constructor & Destructor Documentation
SourceGeo::SourceGeo (Node * node)
Constructs a single texture input.
References DD::Image::GeoOp::display3d_, DD::Image::Op::inputs(), and DD::Image::GeoOp::render_mode_.
Member Function Documentation
Iop * SourceGeo::input_iop () const
Returns the Iop connected to the texture input.
References DD::Image::Op::input0().
Referenced by DD::Image::GeoReader::default_material_iop(), and get_geometry_hash().
void SourceGeo::knobs (Knob_Callback f) virtual
Calls the GeoOp baseclass with source_geo=true so that the display knobs are correct for a Source object.
Reimplemented from DD::Image::GeoOp.
References DD::Image::Knob::HIDDEN.
void SourceGeo::build_input_handles (ViewerContext * ctx)
Constructs the transform to apply before the iop input is followed.
void SourceGeo::init_geoinfo_parms (Scene & scene, GeometryList & out) virtual
Assign all the base parameters for each GeoInfo in the output GeometryList.
References DD::Image::GeoInfoRenderState::castShadow, DD::Image::GeoInfo::display3d, DD::Image::GeoInfo::final_geo, DD::Image::Matrix4::makeIdentity(), DD::Image::GeoInfo::material, DD::Image::GeoInfo::matrix, DD::Image::GeoInfoRenderState::receiveShadow, DD::Image::GeoInfo::recursion_geo, DD::Image::GeoInfo::render_mode, DD::Image::GeoInfo::select_geo, DD::Image::GeoInfo::selectable, DD::Image::GeoOp::selectable_, DD::Image::GeoInfo::selected, DD::Image::GeometryList::size(), and DD::Image::GeoInfo::source_geo.
Referenced by geometry_engine().
void SourceGeo::build_matrix_handles (ViewerContext * ctx, Matrix4 localMatrix) protected
build_handles with the context model matrix multiplied by the local matrix so nodes up the tree are displayed correctly Deprecated. Use GeoOp::build_matrix_handles with a local matrix pointer instead.
References DD::Image::GeoOp::build_matrix_handles().
void SourceGeo::get_geometry_hash () protected virtual
Hash up knobs that affect the geo's material.
Reimplemented from DD::Image::NullGeo.
References DD::Image::GeoOp::geo_hash, DD::Image::Material::get_geometry_hash(), DD::Image::Op::hash(), input_iop(), and DD::Image::Op::iop().
Referenced by DD::Image::ReadGeo::get_geometry_hash().
void SourceGeo::geometry_engine (Scene & scene, GeometryList & out) protected virtual
SourceGeo subclass implementation calls geometry_engine() on each GeoInfo in the local cache list.
Reimplemented from DD::Image::NullGeo.
References init_geoinfo_parms(), DD::Image::Mask_Primitives, and DD::Image::GeometryList::synchronize_objects().
Referenced by DD::Image::ReadGeo::geometry_engine().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk