Nuke Developer Kit (NDK) 13.2.4: DD::Image::DeepLightSample Class Reference
DD::Image::DeepLightSample Class Reference
helper class representing a small float vector, one for each channel in a set
Public Member Functions
DeepLightSample (const ChannelMap &map)
initialise based on a ChannelMap. Set all samples to zero.
DeepLightSample (const ChannelMap &map, const DeepPixel &pixel, int sample, bool fetchOrdered=false)
bool operator== (DeepLightSample &other)
float & operator() (const ChannelMap &map, Channel z)
access the float for a particular channel
float operator() (const ChannelMap &map, Channel z) const
access the float for a particular channel
SampleContainer::iterator begin ()
SampleContainer::iterator end ()
SampleContainer::const_iterator begin () const
SampleContainer::const_iterator end () const
size_t size ()
Detailed Description
helper class representing a small float vector, one for each channel in a set
Constructor & Destructor Documentation
DD::Image::DeepLightSample::DeepLightSample (const ChannelMap & map, const DeepPixel & pixel, int sample, bool fetchOrdered = false) inline
initialise based on a sample from a DeepPixel. if fetchOrdered is true it will use getOrderedSample, otherwise getUnorderedSample
References DD::Image::DeepPixel::channels(), DD::Image::ChannelMap::contains(), DD::Image::DeepPixel::getOrderedSample(), DD::Image::DeepPixel::getUnorderedSample(), and DD::Image::ChannelMap::size().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk