Nuke Developer Kit (NDK) 13.2.4: DD::Image::ImageCacheReadI Class Reference
DD::Image::ImageCacheReadI Class Reference abstract
Holder of temporary data to read files from cache:
Inherited by DD::Image::FileStreamRead, ImageCacheRead, and ImageCacheWriteRead.
Public Member Functions
virtual size_t read (void *to, size_t n)=0
bool tryRead (void *t, size_t n)
virtual void seek (size_t to)=0
virtual void seekRelative (off_t offset)=0
virtual void close ()=0
virtual int uniqueID () const =0
Detailed Description
Holder of temporary data to read files from cache:
Member Function Documentation
virtual size_t DD::Image::ImageCacheReadI::read (void * to, size_t n) pure virtual
Read a block of data from a file opened with Image_Cache::open(). Returns number of bytes read.
Referenced by DD::Image::ViewerCache::read_from_cache().
bool DD::Image::ImageCacheReadI::tryRead (void * t, size_t n) inline
Try to read a certain number of bytes. If it fails to read that number, return false.
virtual void DD::Image::ImageCacheReadI::seek (size_t to) pure virtual
Move the file pointer to an absolute position in the file.
virtual void DD::Image::ImageCacheReadI::seekRelative (off_t offset) pure virtual
Move the file pointer by n bytes.
Referenced by DD::Image::ViewerCache::read_from_cache().
virtual void DD::Image::ImageCacheReadI::close () pure virtual
Close the file and delete the r data structure.
Referenced by DD::Image::ViewerCache::BoxPresent(), and DD::Image::ViewerCache::read_from_cache().
virtual int DD::Image::ImageCacheReadI::uniqueID () const pure virtual
get a unique ID for the memory-cached data, or 0 if the data was not in the memory cache. if the contents of the memory-cached data change (or if the data is removed from the memory cache and then reloaded) this number will increase.
Referenced by DD::Image::ViewerCache::BoxPresent().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk