Nuke Developer Kit (NDK) 13.2.4: DD::Image::IopInfoOwner Class Reference
DD::Image::IopInfoOwner Class Reference
IopInfo holder.
Inherits DD::Image::Info2DProvider.
Inherited by DD::Image::Iop.
Public Types
typedef IopInfo Info
Public Member Functions
const Info & info () const
int x () const
int y () const
int r () const
int t () const
int w () const
int h () const
bool is_constant () const
int clampx (int x) const
int clampy (int y) const
const Format & format () const
const Format & full_size_format () const
int ydirection () const
bool black_outside () const
ChannelMask channels () const
const GeneralInfo & generalInfo () const
const Info2D & info2D () const
int first_frame () const
int last_frame () const
void format (const Format &f)
void full_size_format (const Format &f)
Protected Attributes
Info info_
Detailed Description
IopInfo holder.
Member Function Documentation
const Info & DD::Image::IopInfoOwner::info () const inline
Returns a reference to the data filled in by _validate(). See the description of class Info for what the available data is.
info is only useful if validate(true) has been called otherwise it might change behind your back.
Referenced by DD::Image::RenderScene::_request(), DD::Image::IllumShader::_request(), DD::Image::Render::_request(), DD::Image::NukeWrapper::_request(), DD::Image::UpRez::_validate(), DD::Image::RenderScene::_validate(), DD::Image::DrawIop::_validate(), DD::Image::Transform::_validate(), DD::Image::NukeWrapper::_validate(), DD::Image::Write::_validate(), DD::Image::GeoOp::build_matrix_handles(), DD::Image::Render::buildGeoInfoHandle(), DD::Image::Iop::copy_info(), DD::Image::Iop::doFetchPlane(), DD::Image::Transform::draw_handle(), DD::Image::Write::execute(), DD::Image::Iop::fetchPlane(), DD::Image::PlanarIop::getStripeCount(), DD::Image::Writer::info(), DD::Image::Iop::merge_info(), DD::Image::Iop::mergeFrameRange(), DD::Image::Transform::motionBlurSample(), DD::Image::DrawIop::pixel_engine(), DD::Image::Transform::sample(), DD::Image::Transform::updateConcat(), and DD::Image::Scene::validate().
int DD::Image::IopInfoOwner::x () const inline
Same as info().x();
Referenced by DD::Image::DrawIop::_validate(), DD::Image::Iop::at(), DD::Image::Iop::do_sample_shadowmap(), DD::Image::Render::draw_primitives(), DD::Image::Iop::get(), DD::Image::LightOp::get_shadowing(), DD::Image::DrawIop::pixel_engine(), DD::Image::Iop::request(), DD::Image::Transform::sample(), DD::Image::ToBuffer::to_buffer(), and DD::Image::NukeWrapper::uses_input().
int DD::Image::IopInfoOwner::y () const inline
Same as info().y();
Referenced by DD::Image::DrawIop::_validate(), DD::Image::Iop::at(), DD::Image::Iop::do_sample_shadowmap(), DD::Image::Iop::get(), DD::Image::LightOp::get_shadowing(), DD::Image::DrawIop::pixel_engine(), DD::Image::Iop::request(), and DD::Image::ToBuffer::to_buffer().
int DD::Image::IopInfoOwner::r () const inline
Same as info().r();
Referenced by DD::Image::DrawIop::_validate(), DD::Image::Iop::do_sample_shadowmap(), DD::Image::Transform::draw_handle(), DD::Image::Render::draw_primitives(), DD::Image::Material::engine(), DD::Image::Write::engine(), DD::Image::Iop::get(), DD::Image::LightOp::get_shadowing(), DD::Image::Iop::request(), and DD::Image::ToBuffer::to_buffer().
int DD::Image::IopInfoOwner::t () const inline
Same as info().t();
Referenced by DD::Image::DrawIop::_validate(), DD::Image::Transform::_validate(), DD::Image::Iop::do_sample_shadowmap(), DD::Image::Transform::draw_handle(), DD::Image::LightOp::get_shadowing(), DD::Image::DrawIop::pixel_engine(), DD::Image::Iop::request(), and DD::Image::ToBuffer::to_buffer().
int DD::Image::IopInfoOwner::w () const inline
Same as info().w(), same as r()-l().
Referenced by DD::Image::Transform::_validate(), DD::Image::Iop::doFetchPlane(), DD::Image::Render::get_format_matrix(), DD::Image::Transform::motionBlurSample(), DD::Image::Render::projection_matrix(), and DD::Image::ToBuffer::to_buffer().
int DD::Image::IopInfoOwner::h () const inline
Same as info().h(), same as t()-y().
Referenced by DD::Image::Render::get_format_matrix(), DD::Image::PlanarIop::getStripeCount(), DD::Image::Render::projection_matrix(), and DD::Image::ToBuffer::to_buffer().
int DD::Image::IopInfoOwner::clampx (int x) const inline
Same as info().clampx(x), limits x to the range x() to r()-1.
int DD::Image::IopInfoOwner::clampy (int y) const inline
Same as info().clampy(y), limits y to the range y() to t()-1.
const Format & DD::Image::IopInfoOwner::format () const inline
Same as info().format().
Referenced by DD::Image::Render::_request(), DD::Image::DrawIop::_validate(), DD::Image::RenderScene::build_handles(), DD::Image::Render::camera_matrix(), DD::Image::Transform::draw_handle(), DD::Image::Iop::get(), DD::Image::DrawIop::pixel_engine(), DD::Image::Render::projection_matrix(), DD::Image::VertexContext::sample(), and DD::Image::Scene::validate().
const Format & DD::Image::IopInfoOwner::full_size_format () const inline
Same as info().format();
Referenced by DD::Image::Read::_validate().
int DD::Image::IopInfoOwner::ydirection () const inline
Same as info().ydirection();
Referenced by DD::Image::Transform::_validate(), and DD::Image::ToBuffer::to_buffer().
bool DD::Image::IopInfoOwner::black_outside () const inline
Same as info().black_outside();
Referenced by DD::Image::NukeWrapper::_request(), DD::Image::NukeWrapper::_validate(), DD::Image::Iop::doSample(), DD::Image::Iop::get(), and DD::Image::DrawIop::pixel_engine().
ChannelMask DD::Image::IopInfoOwner::channels () const inline
Same as info().channels();
Referenced by DD::Image::RenderScene::_request(), DD::Image::Iop::_request(), DD::Image::DrawIop::_validate(), DD::Image::Transform::_validate(), DD::Image::NukeWrapper::_validate(), DD::Image::Render::_validate(), DD::Image::Writer::channel_mask(), DD::Image::Iop::copy_info(), DD::Image::Write::depth(), DD::Image::PixelIop::engine(), DD::Image::Reader::from_byte(), DD::Image::Reader::from_float(), DD::Image::Reader::from_short(), DD::Image::Iop::get(), DD::Image::Iop::merge_info(), DD::Image::Iop::request(), DD::Image::VertexContext::sample(), DD::Image::ParticlesSprite::tessellateSprite(), DD::Image::ToBuffer::to_buffer(), and DD::Image::Scene::validate().
int DD::Image::IopInfoOwner::first_frame () const inline
Same as info().first_frame().
Referenced by DD::Image::Iop::mergeFrameRange().
int DD::Image::IopInfoOwner::last_frame () const inline
Same as info().last_frame().
Referenced by DD::Image::Iop::mergeFrameRange().
Member Data Documentation
Info DD::Image::IopInfoOwner::info_ protected
This is the structure returned by info(). It is protected so that _validate() can fill it in, but outside code cannot modify it.
Referenced by DD::Image::UpRez::_validate(), DD::Image::RenderScene::_validate(), DD::Image::IllumShader::_validate(), DD::Image::DrawIop::_validate(), DD::Image::Transform::_validate(), DD::Image::NukeWrapper::_validate(), DD::Image::Write::_validate(), DD::Image::Render::_validate(), DD::Image::Iop::_validate(), DD::Image::Black::Black(), DD::Image::Iop::clear_info(), DD::Image::Iop::copy_info(), DD::Image::Transform::degenerate(), DD::Image::Write::execute(), DD::Image::Iop::get(), DD::Image::Render::get_format_matrix(), DD::Image::Iop::Iop(), DD::Image::Iop::merge_info(), DD::Image::Iop::mergeFrameRange(), DD::Image::RenderScene::projection_matrix(), DD::Image::Iop::request(), DD::Image::Transform::setclip(), DD::Image::ToBuffer::to_buffer(), and DD::Image::Transform::updateConcat().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk