Nuke Developer Kit (NDK) 13.2.4: DD::Image::OpTree Class Reference
DD::Image::OpTree Class Reference
Public Member Functions
OpTree (Op *lpRoot=nullptr)
void abort ()
void cancel ()
void clearAbortedFlag ()
void clearCancelledFlag ()
bool wasAborted () const
bool wasCancelled () const
void setExecuting (bool lExecuting)
bool isExecuting () const
bool addMessageOp (Op *lpOp)
Called when an op in the tree enters an error state; returns true iff not in the set.
bool removeMessageOp (Op *lpOp)
Called when an op in the tree has its error cleared; returns true iff in the set.
bool hasMessage () const
Returns true if any op in this tree has a message set.
bool hasError () const
Returns true if any op in this tree has an error set.
Op * getFirstOpWithMessage () const
Returns the first op in the tree with a message set, or NULL if none do.
Op * getFirstOpWithError () const
Returns the first op in the tree with an error set, or NULL if none do.
void setNewRoot (Op *lpRoot)
Op * getRoot () const
int getDebugIndex () const
Information about an individual tree for debugging purposes.
void setDebugLabel (const std::string &lrLabel)
const std::string & getDebugLabel () const
int getNumMessageOps () const
Detailed Description
This class encapsulates a tree of ops to process, and associated states for that processing. It also manages a list of observers to notify when ops' error states change.
Member Function Documentation
void OpTree::setNewRoot (Op * lpRoot)
Changes the tree root to a different op, updating references appropriately; not thread safe. Also clears aborted and cancelled flags.
References DD::Image::GetAllConnectedOps(), DD::Image::GetOpText(), and DD::Image::GetOpTreeText().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk