Nuke Developer Kit (NDK) 13.2.4: DD::Image::ViewFrustum Class Reference
DD::Image::ViewFrustum Class Reference
Public Member Functions
ViewFrustum ()
Default constructor.
ViewFrustum (const CameraOp &camera)
Constructor by camera.
ViewFrustum (ViewerContext *ctx, const Box &rect)
void update (const CameraOp &camera)
Update frustum plane in world coordinate according to camera data.
void update (const CameraOp &camera, const Matrix4 &m)
Update frustum plane according to Matrix4 transformation.
const Plane & getPlane (FrustumPlane plane) const
Get a frustum plane.
FrustumVisibility getVisibility (const PointList *plist) const
Test the visibility of a polygon inside a list of coplanar vertices.
FrustumVisibility getVisibility (const Vector3 *points, const Primitive *prim, unsigned face) const
Test the visibility a primitive face.
Detailed Description
View Frustum class. Define the camera view frustum with a list of planes. A plane is defined in world coordinate. It is used to determine polygon visibility.
Constructor & Destructor Documentation
DD::Image::ViewFrustum::ViewFrustum (ViewerContext * ctx, const Box & rect)
Construct a frustum using the 2D rectangle projected onto the camera's near and far clipping planes.
References DD::Image::Box::r(), DD::Image::Box::t(), DD::Image::ViewerContext::viewport(), DD::Image::Box::x(), and DD::Image::Box::y().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk