Nuke Developer Kit (NDK) 13.2.4: DD::Image::GeneralInfo Class Reference
DD::Image::GeneralInfo Class Reference
Base class for defining a time bounded region.
Inherited by DD::Image::Info2D.
Public Member Functions
int firstFrame () const
get the first frame in the range
int first_frame () const
get the first frame in the range
int lastFrame () const
get the last frame in the range
int last_frame () const
get the last frame in the range
void setFirstFrame (int v)
set the first frame in the range
void setLastFrame (int v)
set the last frame in the range
void first_frame (int v)
set the first frame in the range
void last_frame (int v)
set the last frame in the range
void setFrameRange (FrameRange frameRange)
Detailed Description
Base class for defining a time bounded region.
Member Function Documentation
int DD::Image::GeneralInfo::first_frame () const inline
get the first frame in the range
First frame in the range of the clip this Iop produces.
Referenced by DD::Image::Iop::Iop(), DD::Image::Iop::mergeFrameRange(), and DD::Image::Reader::Reader().
int DD::Image::GeneralInfo::last_frame () const inline
get the last frame in the range
Last frame in the range of the clip this Iop produces.
Referenced by DD::Image::Iop::Iop(), DD::Image::Iop::mergeFrameRange(), and DD::Image::Reader::Reader().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk