Nuke Developer Kit (NDK) 13.2.4: DD::Image::ShutterControls Class Reference
DD::Image::ShutterControls Class Reference
Public Types
enum OffsetEnum { eCentredOffset, eStartOffset, eEndOffset, eCustomOffset }
Public Member Functions
ShutterControls (double duration=0.5, OffsetEnum offset=eStartOffset, double customOffset=0.0)
Constructor.
void knobs (Knob_Closure &f, bool earlyStore=false, const char *durationName="shutter", const char *offsetTypeName="shutteroffset", const char *customOffsetName="shuttercustomoffset")
double getDuration () const
double calcOffset () const
OffsetEnum getOffset () const
double getCustomOffset () const
void setDuration (double v)
void setOffset (OffsetEnum v)
void setCustomOffset (double v)
Knob * getDurationKnob ()
Knob * getOffsetKnob ()
Knob * getCustomOffsetKnob ()
void append (DD::Image::Hash &hash)
Detailed Description
Class used to standardise shutter controls throughout NUKE
Member Enumeration Documentation
enum DD::Image::ShutterControls::OffsetEnum
Enum used to specify what kind of shutter offset we have
Member Function Documentation
void DD::Image::ShutterControls::knobs (Knob_Closure & f, bool earlyStore = false, const char * durationName = "shutter", const char * offsetTypeName = "shutteroffset", const char * customOffsetName = "shuttercustomoffset")
The owner of this object must call this in their Op::knobs() function
References DD::Image::Knob::EARLY_STORE, DD::Image::Enumeration_knob(), DD::Image::Obsolete_knob(), DD::Image::SetFlags(), and DD::Image::Tooltip().
Referenced by DD::Image::Transform::motionblur_knobs().
double DD::Image::ShutterControls::getDuration () const inline
The duration
Referenced by DD::Image::Transform::_validate(), and DD::Image::Transform::append().
double DD::Image::ShutterControls::calcOffset () const
Offset to the start of the shutter period from integer frame number
Referenced by DD::Image::Transform::_validate(), and DD::Image::Transform::append().
OffsetEnum DD::Image::ShutterControls::getOffset () const inline
The type of offset.
double DD::Image::ShutterControls::getCustomOffset () const inline
The Offset if the enum is set to eCustomOffset
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk