Nuke Developer Kit (NDK) 13.2.4: DD::Image::DeepWriterOwner Class Reference
DD::Image::DeepWriterOwner Class Reference abstract
Public Member Functions
virtual Op * op ()=0
virtual DeepOp * input ()=0
virtual const char * filename () const =0
virtual const ChannelSet & channels ()=0
Friends
class DeepWriter
Detailed Description
Helper class for DeepWriter
Member Function Documentation
virtual Op* DD::Image::DeepWriterOwner::op () pure virtual
return a pointer to the Op
Referenced by DD::Image::DeepWriter::closeFile(), and DD::Image::DeepWriter::openFile().
virtual DeepOp* DD::Image::DeepWriterOwner::input () pure virtual
return the DeepOp to write out
Referenced by DD::Image::DeepWriter::input().
virtual const char* DD::Image::DeepWriterOwner::filename () const pure virtual
return the filename to write to
Referenced by DD::Image::DeepWriter::closeFile(), and DD::Image::DeepWriter::openFile().
virtual const ChannelSet& DD::Image::DeepWriterOwner::channels () pure virtual
return the channels to write
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk