Nuke Developer Kit (NDK) 13.2.4: DD::Image::ShutDownListener Class Reference
DD::Image::ShutDownListener Class Reference abstract
Inherited by StaticLightContext.
Public Member Functions
ShutDownListener ()
virtual ~ShutDownListener ()
virtual void shutdownEvent ()=0
void registerListener ()
void unregisterListener ()
Detailed Description
! Simple interface class for Shutdown events, Derive from this in systems that need to know about shutdown
Constructor & Destructor Documentation
DD::Image::ShutDownListener::ShutDownListener ()
! C'tor Auto-magically registers with the shutdown system
References registerListener().
DD::Image::ShutDownListener::~ShutDownListener () virtual
! D'tor Auto-magically unregisters with the shutdown system
References unregisterListener().
Member Function Documentation
virtual void DD::Image::ShutDownListener::shutdownEvent () pure virtual
! Pure abstract function. Will be called during application shutdown. It is safe to delete this or otherwise unregister this object from the shutdown system.
void DD::Image::ShutDownListener::registerListener ()
! register Called by the c'tor, registers with the shutdown system. Must not be called during shutdownEvent()
References DD::Image::ShutdownBroadcaster::Get(), and DD::Image::ShutdownBroadcaster::registerShutdownListener().
Referenced by ShutDownListener().
void DD::Image::ShutDownListener::unregisterListener ()
! deregister Called by the d'tor, unregisters with the shutdown system. Can be called during shutdownEvent()
References DD::Image::ShutdownBroadcaster::Get(), and DD::Image::ShutdownBroadcaster::unregisterShutdownListener().
Referenced by ~ShutDownListener().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk