Nuke Developer Kit (NDK) 13.2.4: DD::Image::FileRead Class Reference
DD::Image::FileRead Class Reference abstract
Inherited by DD::Image::Read, and DD::Image::ReadGeo.
Public Member Functions
virtual const char * getFilename () const =0
Static Public Member Functions
static void closeFile (const std::string &filename)
Protected Member Functions
virtual void close ()=0
! should be overriden to close the file
Detailed Description
Interface that is implemented by objects that retain an open file handle to some file, so that Execute can make sure that all open handles on a file are closed before it is written to. Read and ReadGeo inherit from this.
Member Function Documentation
virtual const char* DD::Image::FileRead::getFilename () const pure virtual
! should be overriden to return the filename currently in use. can return NULL if not present
Referenced by closeFile().
void DD::Image::FileRead::closeFile (const std::string & filename) static
call close() on all FileRead objects whose filename is /filename/
References close(), getFilename(), DD::Image::Lock::lock(), and DD::Image::Lock::unlock().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk