Nuke Developer Kit (NDK) 13.2.4: DD::Image::DeepWriter Class Reference
DD::Image::DeepWriter Class Reference abstract
Inherits DD::Image::FileHandler.
Classes
class Description
Public Member Functions
DeepWriter (DeepWriterOwner *owner)
DeepWriter (const DeepWriter &other)
void operator= (const DeepWriter &other)
left unimplemented
DeepOp * input ()
left unimplemented
FILE * openFile ()
void closeFile (FILE *f)
virtual void execute ()=0
Protected Attributes
DeepWriterOwner * _owner
Detailed Description
Class for plugins that wish to write out deep data. The DeepWriters are selected by the DeepWrite node.
Member Function Documentation
DeepOp * DD::Image::DeepWriter::input ()
left unimplemented
get the deep op to use as the source of data for the write
References DD::Image::DeepWriterOwner::input().
FILE * DD::Image::DeepWriter::openFile ()
open a temporary file and return it
References DD::Image::Op::error(), DD::Image::DeepWriterOwner::filename(), and DD::Image::DeepWriterOwner::op().
void DD::Image::DeepWriter::closeFile (FILE * f)
close the temporary file and rename it to the full version
References DD::Image::DeepWriterOwner::filename(), DD::Image::DeepWriterOwner::op(), and DD::Image::RenameTempToFinal().
virtual void DD::Image::DeepWriter::execute () pure virtual
virtual function to be implemented. should write out the Deep data available on input() to the filename on _owner->filename(). Can use helper functions openFile() and closeFile() for dealing with temporary filenames.
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk