Nuke Developer Kit (NDK) 13.2.4: DD::Image::ShutdownBroadcaster Class Reference
DD::Image::ShutdownBroadcaster Class Reference
Public Member Functions
void registerShutdownListener (ShutDownListener *)
void unregisterShutdownListener (ShutDownListener *)
Static Public Member Functions
static ShutdownBroadcaster * Get ()
static void Destroy ()
Detailed Description
! ShutdownBroadcaster Classes which need to deallocate extra, global, resources on shutdown should register themselves here.
Member Function Documentation
ShutdownBroadcaster * DD::Image::ShutdownBroadcaster::Get () static
! Lazily create and/or return the Broadcaster
Referenced by DD::Image::ShutDownListener::registerListener(), and DD::Image::ShutDownListener::unregisterListener().
void DD::Image::ShutdownBroadcaster::Destroy () static
! Managed Destruction Emits the shutdownEvent()
Referenced by DD::Image::PostAbortTeardown().
void DD::Image::ShutdownBroadcaster::registerShutdownListener (ShutDownListener * listener)
! RegisterShoutdownListener Systems which need to deallocate extra, global, resources on shutdown should register themselves here.
Referenced by DD::Image::ShutDownListener::registerListener().
void DD::Image::ShutdownBroadcaster::unregisterShutdownListener (ShutDownListener * listener)
! UnregisterShoutdownListener System which have registered themselves as Shutdown observers should deregister here.
Referenced by DD::Image::ShutDownListener::unregisterListener().
©2022 The Foundry Visionmongers, Ltd. All Rights Reserved.
www.thefoundry.co.uk